[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests -B"]

[start]
cmd = "java -Xmx400m -Xss512k -XX:MaxMetaspaceSize=128m -jar target/rentmybike-backend-0.0.1-SNAPSHOT.jar"
