package com.rentmybike.common.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.proxy.HibernateProxy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Abstract base entity inherited by all JPA entities in RentMyBike.
 * Abstrakte Basisentität, die von allen JPA-Entitäten in RentMyBike geerbt wird.
 *
 * <p>Provides / Bietet:
 * <ul>
 *   <li>UUID primary key (auto-generated, not sequential — avoids enumeration attacks)</li>
 *   <li>createdAt — auto-filled on INSERT by Spring Data Auditing</li>
 *   <li>updatedAt — auto-updated on every UPDATE by Spring Data Auditing</li>
 *   <li>deletedAt — soft-delete marker (null = active, not-null = deleted)</li>
 * </ul>
 *
 * <p>Requires {@code @EnableJpaAuditing} on the main application class.
 * <p>Erfordert {@code @EnableJpaAuditing} auf der Hauptanwendungsklasse.
 */
@MappedSuperclass
@Getter
@Setter
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * UUID primary key — auto-generated by the database.
     * UUID-Primärschlüssel — wird automatisch von der Datenbank generiert.
     *
     * <p>Using UUID instead of Long prevents ID enumeration attacks.
     * <p>UUID statt Long verhindert ID-Enumerierungsangriffe.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * Timestamp of record creation — set once on INSERT, never changes.
     * Zeitstempel der Datensatzerstellung — wird beim INSERT gesetzt, ändert sich nie.
     */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of last modification — auto-updated on every save().
     * Zeitstempel der letzten Änderung — wird bei jedem save() automatisch aktualisiert.
     */
    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Soft-delete marker — null means the record is active.
     * Soft-Delete-Marker — null bedeutet, der Datensatz ist aktiv.
     *
     * <p>We never hard-delete records to preserve booking and review history.
     * <p>Wir löschen niemals endgültig, um Buchungs- und Bewertungshistorie zu bewahren.
     *
     * <p>Usage: set to LocalDateTime.now() to "delete" a record.
     * <p>Verwendung: auf LocalDateTime.now() setzen, um einen Datensatz zu "löschen".
     */
    @Column
    private LocalDateTime deletedAt;

    /**
     * Convenience method: checks if this record has been soft-deleted.
     * Hilfsmethode: Prüft, ob dieser Datensatz soft-gelöscht wurde.
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Marks this record as soft-deleted by setting deletedAt to now.
     * Markiert diesen Datensatz als soft-gelöscht, indem deletedAt auf jetzt gesetzt wird.
     *
     * <p>Call {@code repository.save(entity)} after this to persist the change.
     * <p>Rufe {@code repository.save(entity)} danach auf, um die Änderung zu persistieren.
     */
    public void softDelete() {
        this.deletedAt = LocalDateTime.now();
    }

    /**
     * Entity equality based on persistent identity (id), not field values.
     * Two transient (unsaved, id == null) entities are never equal to each
     * other — only to themselves — to avoid colliding in a Set before they
     * have a real identity. Handles Hibernate proxies so that a proxy and
     * its initialized counterpart compare equal.
     * Entitätsgleichheit basierend auf der persistenten Identität (id), nicht
     * auf Feldwerten. Zwei transiente (nicht gespeicherte, id == null)
     * Entitäten sind niemals gleich zueinander — nur zu sich selbst —, um
     * Kollisionen in einem Set zu vermeiden, bevor sie eine echte Identität
     * haben. Behandelt Hibernate-Proxys, damit ein Proxy und sein
     * initialisiertes Gegenstück als gleich verglichen werden.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> thisClass = this instanceof HibernateProxy
                ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass()
                : this.getClass();
        Class<?> otherClass = o instanceof HibernateProxy
                ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass()
                : o.getClass();
        if (!thisClass.equals(otherClass)) return false;
        BaseEntity other = (BaseEntity) o;
        return id != null && id.equals(other.getId());
    }

    /**
     * Constant hash code so that an entity's hash never changes as it
     * transitions from transient (id == null) to persistent — required by
     * the Set/Map contract, since {@link #equals} depends on id.
     * Konstanter Hashcode, damit sich der Hash einer Entität nie ändert,
     * wenn sie von transient (id == null) zu persistent übergeht —
     * erforderlich durch den Set/Map-Vertrag, da {@link #equals} von id
     * abhängt.
     */
    @Override
    public int hashCode() {
        return Objects.hash(getClass().hashCode());
    }
}
