package com.rentmybike.audit.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * An immutable, append-only record of an admin/moderation/account event.
 * Ein unveränderlicher, nur anfügbarer Eintrag eines Admin-/Moderations-/Kontoereignisses.
 *
 * <p>Does NOT extend {@code BaseEntity} — there is no {@code updatedAt} or
 * {@code deletedAt} here, because audit log rows are never modified or
 * removed once written. {@code id} and {@code createdAt} are handled
 * directly on this entity instead, mirroring {@code BaseEntity}'s approach
 * (UUID primary key generated by the database, {@code createdAt} auto-filled
 * by Spring Data Auditing on INSERT).
 * <p>Erweitert NICHT {@code BaseEntity} — es gibt hier kein {@code updatedAt}
 * oder {@code deletedAt}, da Audit-Log-Zeilen nach dem Schreiben nie verändert
 * oder entfernt werden. {@code id} und {@code createdAt} werden direkt auf
 * dieser Entity gehandhabt, analog zu {@code BaseEntity} (von der Datenbank
 * generierter UUID-Primärschlüssel, {@code createdAt} automatisch befüllt
 * durch Spring Data Auditing beim INSERT).
 *
 * <p>{@code actorName} is a denormalized snapshot of the acting user's name
 * at the time of the event, so the log stays readable even if the actor's
 * account is later renamed or soft-deleted. {@code actorId} is nullable to
 * leave room for future system-triggered events with no human actor.
 * <p>{@code actorName} ist eine denormalisierte Momentaufnahme des Namens des
 * Akteurs zum Zeitpunkt des Ereignisses, damit das Protokoll auch dann lesbar
 * bleibt, wenn das Konto des Akteurs später umbenannt oder soft-gelöscht
 * wird. {@code actorId} ist nullable, um Raum für künftige systemausgelöste
 * Ereignisse ohne menschlichen Akteur zu lassen.
 *
 * <p>Maps to PostgreSQL table {@code audit_log}.
 * <p>Entspricht der PostgreSQL-Tabelle {@code audit_log}.
 */
@Entity
@Table(name = "audit_log")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EntityListeners(AuditingEntityListener.class)
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * The admin or user who triggered the event — null for system events.
     * Der Admin oder Benutzer, der das Ereignis ausgelöst hat — null bei Systemereignissen.
     */
    @Column(name = "actor_id", updatable = false)
    private UUID actorId;

    /**
     * Denormalized snapshot of the actor's display name at event time.
     * Denormalisierte Momentaufnahme des Anzeigenamens des Akteurs zum Ereigniszeitpunkt.
     */
    @Column(name = "actor_name", updatable = false, length = 200)
    private String actorName;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, updatable = false, columnDefinition = "VARCHAR(50)")
    private AuditAction action;

    /** e.g. "USER" / "BIKE" / "BOOKING" — the kind of entity affected. */
    @Column(name = "target_type", nullable = false, updatable = false, length = 40)
    private String targetType;

    /** The affected entity's id — nullable for events with no single target. */
    @Column(name = "target_id", updatable = false)
    private UUID targetId;

    /** Free-text context, e.g. a bike rejection reason — nullable. */
    @Column(updatable = false, columnDefinition = "TEXT")
    private String details;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
